<a href="https://colab.research.google.com/github/sukhdhillion321-web/notes/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
data =pd.Series([1,2,3,4,5])
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
data=pd.Series([1,2,3,4,5],dtype=float)
data

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [ ]:
data.dtype

dtype('int64')

In [ ]:
data.values

array([1, 2, 3, 4, 5])

In [ ]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
print(data.name)

None

In [ ]:
data.name="sukh"
data

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
Name: sukh, dtype: float64

In [ ]:
data=pd.Series([1,2,3,4,5],dtype=int)
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#indexing
data[0]

np.int64(1)

In [ ]:
data[0:2]

0    1
1    2
dtype: int64

In [ ]:
data[::2]

0    1
2    3
4    5
dtype: int64

In [ ]:
#iloc<- uses location(loacation based indexing)
data.iloc[3]

np.int64(4)

In [ ]:
data.iloc[[1,3,4]]

1    2
3    4
4    5
dtype: int64

In [ ]:
index=["workout","excercise","eat","sleep","walk"]

In [ ]:
data.index=index
data

workout      1
excercise    2
eat          3
sleep        4
walk         5
dtype: int64

In [ ]:
data["eat"]

np.int64(3)

In [ ]:
#loc <- label based indexing
#stop value is also included
data.loc["eat"]

np.int64(3)

In [ ]:
data.loc["sleep"]

np.int64(4)

In [ ]:
details={
    "name":"sukh",
    "age":20,
    "job":"engineer"
}

In [ ]:
my_series=pd.Series(details,name="details")
my_series

name        sukh
age           20
job     engineer
Name: details, dtype: object

In [3]:
h={
    "name":["sukh","raj","gur","man"],
    "roll_no":["02","03","04","05"],
    "hobies":["dance","singing","reading","writing"],
    "favourite_colors":["red","black","yellow","orange"]
}

In [4]:
df=pd.DataFrame(h)
df

   name roll_no   hobies favourite_colors
0  sukh      02    dance              red
1   raj      03  singing            black
2   gur      04  reading           yellow
3   man      05  writing           orange

In [7]:
df.head(2)

   name roll_no   hobies favourite_colors
0  sukh      02    dance              red
1   raj      03  singing            black

In [8]:
df.tail(2)

  name roll_no   hobies favourite_colors
2  gur      04  reading           yellow
3  man      05  writing           orange

In [9]:
df.iloc[1:3]

  name roll_no   hobies favourite_colors
1  raj      03  singing            black
2  gur      04  reading           yellow

In [10]:
df.loc[1:3,["roll_no","name"]]

  roll_no name
1      03  raj
2      04  gur
3      05  man

In [11]:

df[["name","roll_no"]]

   name roll_no
0  sukh      02
1   raj      03
2   gur      04
3   man      05

In [12]:
df.drop("hobies",axis=1)

   name roll_no favourite_colors
0  sukh      02              red
1   raj      03            black
2   gur      04           yellow
3   man      05           orange

In [13]:
df

   name roll_no   hobies favourite_colors
0  sukh      02    dance              red
1   raj      03  singing            black
2   gur      04  reading           yellow
3   man      05  writing           orange

In [14]:
df.drop("hobies",axis=1,inplace=True)

In [15]:
df

   name roll_no favourite_colors
0  sukh      02              red
1   raj      03            black
2   gur      04           yellow
3   man      05           orange

In [16]:
df.shape

(4, 3)

In [17]:
df.dtypes

name                object
roll_no             object
favourite_colors    object
dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              4 non-null      object
 1   roll_no           4 non-null      object
 2   favourite_colors  4 non-null      object
dtypes: object(3)
memory usage: 228.0+ bytes

In [19]:
df.describe()

        name roll_no favourite_colors
count      4       4                4
unique     4       4                4
top     sukh      02              red
freq       1       1                1

In [20]:
df.rename(columns={"favourite_colors":"colors"},inplace=True)
df

   name roll_no  colors
0  sukh      02     red
1   raj      03   black
2   gur      04  yellow
3   man      05  orange

In [21]:
df["colors"].value_counts()

colors
red       1
black     1
yellow    1
orange    1
Name: count, dtype: int64